# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(357, 189)
        self.resultLabel = QtWidgets.QLabel(Dialog)
        self.resultLabel.setGeometry(QtCore.QRect(10, 140, 161, 20))
        self.resultLabel.setText("")
        self.resultLabel.setObjectName("resultLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 30, 231, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(14, -1, 15, 5)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setEnabled(True)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.gelirBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.gelirBox.setObjectName("gelirBox")
        self.verticalLayout.addWidget(self.gelirBox)
        self.gelirButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.gelirButton.setObjectName("gelirButton")
        self.verticalLayout.addWidget(self.gelirButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(11, -1, 15, 5)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setEnabled(True)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.giderBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.giderBox.setObjectName("giderBox")
        self.verticalLayout_2.addWidget(self.giderBox)
        self.giderButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.giderButton.setObjectName("giderButton")
        self.verticalLayout_2.addWidget(self.giderButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.dateLabel = QtWidgets.QLabel(Dialog)
        self.dateLabel.setGeometry(QtCore.QRect(50, 10, 120, 13))
        self.dateLabel.setObjectName("dateLabel")
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setGeometry(QtCore.QRect(253, 160, 91, 23))
        self.clearButton.setObjectName("clearButton")
        self.showDBButton = QtWidgets.QPushButton(Dialog)
        self.showDBButton.setGeometry(QtCore.QRect(253, 130, 91, 23))
        self.showDBButton.setObjectName("showDBButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Gelir"))
        self.gelirButton.setText(_translate("Dialog", "Ekle"))
        self.label_3.setText(_translate("Dialog", "Gider"))
        self.giderButton.setText(_translate("Dialog", "Ekle"))
        self.label_2.setText(_translate("Dialog", "Tarih:"))
        self.dateLabel.setText(_translate("Dialog", "a"))
        self.clearButton.setText(_translate("Dialog", "Tum Verileri Sil"))
        self.showDBButton.setText(_translate("Dialog", "Verileri Goruntule"))
