# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(713, 277)
        self.resultLabel = QtWidgets.QLabel(Dialog)
        self.resultLabel.setGeometry(QtCore.QRect(280, 10, 161, 20))
        self.resultLabel.setText("")
        self.resultLabel.setObjectName("resultLabel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.dateLabel = QtWidgets.QLabel(Dialog)
        self.dateLabel.setGeometry(QtCore.QRect(50, 10, 120, 13))
        self.dateLabel.setObjectName("dateLabel")
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setGeometry(QtCore.QRect(550, 230, 131, 23))
        self.clearButton.setObjectName("clearButton")
        self.showDBButton = QtWidgets.QPushButton(Dialog)
        self.showDBButton.setGeometry(QtCore.QRect(410, 230, 131, 23))
        self.showDBButton.setObjectName("showDBButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 554, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(14, -1, 15, 5)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setEnabled(True)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.gelirBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gelirBox.sizePolicy().hasHeightForWidth())
        self.gelirBox.setSizePolicy(sizePolicy)
        self.gelirBox.setStyleSheet("QLineEdit{\n"
"    margin-bottom:31px;\n"
"}")
        self.gelirBox.setObjectName("gelirBox")
        self.verticalLayout.addWidget(self.gelirBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setContentsMargins(14, -1, 15, 5)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setEnabled(True)
        self.label_4.setStyleSheet("QLabel{\n"
"    margin-left:15px;\n"
"}")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.aciklama = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.aciklama.setStyleSheet("QLineEdit{\n"
"    margin-bottom:31px;\n"
"}")
        self.aciklama.setObjectName("aciklama")
        self.verticalLayout_3.addWidget(self.aciklama)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setEnabled(True)
        self.label_5.setStyleSheet("QLabel{\n"
"    margin-left:13px;\n"
"}")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.kategoriBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.kategoriBox.setStyleSheet("QComboBox{\n"
"    margin-bottom:35px;\n"
"    margin-left:10px;\n"
"    margin-right:10px;\n"
"}")
        self.kategoriBox.setObjectName("kategoriBox")
        self.kategoriBox.addItem("")
        self.kategoriBox.addItem("")
        self.kategoriBox.addItem("")
        self.kategoriBox.addItem("")
        self.kategoriBox.addItem("")
        self.kategoriBox.addItem("")
        self.kategoriBox.addItem("")
        self.kategoriBox.addItem("")
        self.verticalLayout_2.addWidget(self.kategoriBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setEnabled(True)
        self.label_6.setStyleSheet("QLabel{\n"
"    margin-left:13px;\n"
"}")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.ozelKategori = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ozelKategori.setStyleSheet("QLineEdit{\n"
"    margin-bottom:35px;\n"
"    margin-left:10px;\n"
"    margin-right:10px;\n"
"}")
        self.ozelKategori.setObjectName("ozelKategori")
        self.verticalLayout_4.addWidget(self.ozelKategori)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gelirButton = QtWidgets.QPushButton(Dialog)
        self.gelirButton.setGeometry(QtCore.QRect(260, 170, 118, 25))
        self.gelirButton.setStyleSheet("QPushButton{\n"
"    margin-top:5px;\n"
"}")
        self.gelirButton.setObjectName("gelirButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Tarih:"))
        self.dateLabel.setText(_translate("Dialog", "a"))
        self.clearButton.setText(_translate("Dialog", "Tum Verileri Sil"))
        self.showDBButton.setText(_translate("Dialog", "Verileri Goruntule"))
        self.label.setText(_translate("Dialog", "Miktar"))
        self.label_4.setText(_translate("Dialog", "Aciklama"))
        self.label_5.setText(_translate("Dialog", "Kategori"))
        self.kategoriBox.setItemText(0, _translate("Dialog", "Belirtilmemis"))
        self.kategoriBox.setItemText(1, _translate("Dialog", "Ev Alisverisi"))
        self.kategoriBox.setItemText(2, _translate("Dialog", "Online Odemeler"))
        self.kategoriBox.setItemText(3, _translate("Dialog", "Fatura"))
        self.kategoriBox.setItemText(4, _translate("Dialog", "Kira"))
        self.kategoriBox.setItemText(5, _translate("Dialog", "Yiyecek"))
        self.kategoriBox.setItemText(6, _translate("Dialog", "Kiyafet"))
        self.kategoriBox.setItemText(7, _translate("Dialog", "Yakit"))
        self.label_6.setText(_translate("Dialog", "Ozel Kategori"))
        self.gelirButton.setText(_translate("Dialog", "Ekle"))
